add smolbs

diff --git a/bin/xtr b/bin/xtr
--- a/bin/xtr
+++ b/bin/xtr
@@ -1,4 +1,5 @@
 #!/usr/bin/env sh
+# kanged from an extract.plugin.zsh somewhere
 
 usage() {
     cat >&2 <<EOF
@@ -6,31 +7,73 @@ Usage:
     $(basename $0) [OPTIONS...] <files...>
 
 Options:
-    -h, --help
-        shows this screen
+    -h, --help	shows this screen
+    -r, --remove    Remove archive.
 EOF
 	exit $1
 }
 
 test $# = 0 && usage 1
 
-while test $# -gt 0; do
-	case $1 in -h|--help) usage 0;; esac
-	test -f "$1" || echo "file '$1' doesn't exist, skipping..." >&2
-	case $1 in
-		*.tar.bz2)   tar xvjf $1     ;;
-		*.tar.gz)    tar xvzf $1     ;;
-		*.bz2)       bunzip2 $1      ;;
-		*.rar)       unrar x $1      ;;
-		*.gz)        gunzip $1       ;;
-		*.tar)       tar xvf $1      ;;
-		*.tbz2)      tar xvjf $1     ;;
-		*.tgz)       tar xvzf $1     ;;
-		*.tar.*)     tar xf $1       ;;
-		*.zip)       unzip $1        ;;
-		*.Z)         uncompress $1   ;;
-		*.7z)        7z x $1         ;;
-		*) echo "'$1' cannot be extracted via $(basename $0), skipping..." >&2;;
-	esac
-	shift 1
-done
+extract() {
+	local remove_archive
+	local success
+	local extract_dir
+
+	remove_archive=1
+	if [[ "$1" == "-r" ]] || [[ "$1" == "--remove" ]]; then
+		remove_archive=0
+		shift
+	fi
+
+	while (( $# > 0 )); do
+		if [[ ! -f "$1" ]]; then
+			echo "extract: '$1' is not a valid file" >&2
+			shift
+			continue
+		fi
+
+		success=0
+		extract_dir="${1:t:r}"
+		case "$1" in
+			(*.tar.gz|*.tgz) (( $+commands[pigz] )) && { pigz -dc "$1" | tar xv } || tar zxvf "$1" ;;
+			(*.tar.bz2|*.tbz|*.tbz2) tar xvjf "$1" ;;
+			(*.tar.xz|*.txz)
+				tar --xz --help &> /dev/null \
+				&& tar --xz -xvf "$1" \
+				|| xzcat "$1" | tar xvf - ;;
+			(*.tar.zma|*.tlz)
+				tar --lzma --help &> /dev/null \
+				&& tar --lzma -xvf "$1" \
+				|| lzcat "$1" | tar xvf - ;;
+			(*.tar) tar xvf "$1" ;;
+			(*.gz) (( $+commands[pigz] )) && pigz -d "$1" || gunzip "$1" ;;
+			(*.bz2) bunzip2 "$1" ;;
+			(*.xz) unxz "$1" ;;
+			(*.lzma) unlzma "$1" ;;
+			(*.Z) uncompress "$1" ;;
+			(*.zip|*.war|*.jar|*.sublime-package|*.ipsw|*.xpi|*.apk) unzip "$1" -d $extract_dir ;;
+			(*.rar) unrar x -ad "$1" ;;
+			(*.7z) 7za x "$1" ;;
+			(*.deb)
+				mkdir -p "$extract_dir/control"
+				mkdir -p "$extract_dir/data"
+				cd "$extract_dir"; ar vx "../${1}" > /dev/null
+				cd control; tar xzvf ../control.tar.gz
+				cd ../data; extract ../data.tar.*
+				cd ..; rm *.tar.* debian-binary
+				cd ..
+			;;
+			(*)
+				echo "extract: '$1' cannot be extracted" >&2
+				success=1
+			;;
+		esac
+
+		(( success = $success > 0 ? $success : $? ))
+		(( $success == 0 )) && (( $remove_archive == 0 )) && rm "$1"
+		shift
+	done
+}
+
+extract "$@"
